<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import { adminApi } from '@/api/admin'
import { formatDateTime, orderStatusLabel, orderStatusType } from '@/constants/order'
import type { AdminOrder, OrderStatus, Pagination } from '@/types'

const loading = ref(true), detailVisible = ref(false), current = ref<AdminOrder | null>(null)
const items = ref<AdminOrder[]>([])
const pagination = ref<Pagination>({ page: 1, pageSize: 10, total: 0, totalPages: 0 })
const filters = reactive({ keyword: '', status: '' as '' | OrderStatus })
async function load(page = 1) { loading.value = true; try { const result = await adminApi.orders({ page, pageSize: 10, keyword: filters.keyword || undefined, status: filters.status || undefined }); items.value = result.data.items; pagination.value = result.data.pagination } finally { loading.value = false } }
function detail(row: AdminOrder) { current.value = row; detailVisible.value = true }
async function change(row: AdminOrder, status: OrderStatus, text: string) { await ElMessageBox.confirm(`确定${text}订单 ${row.orderNo} 吗？`, text, { type: 'warning' }); await adminApi.setOrderStatus(row.id, status); ElMessage.success(`订单已${text}`); detailVisible.value = false; await load(pagination.value.page) }
onMounted(() => load())
</script>

<template>
  <section><div :class="$style.heading"><div><span>ORDERS</span><h1>订单管理</h1><p>检索全站订单并推进履约状态。</p></div></div>
    <div :class="$style.toolbar"><el-input v-model="filters.keyword" placeholder="订单号 / 收件人 / 用户邮箱" clearable :prefix-icon="Search" @keyup.enter="load(1)" /><el-select v-model="filters.status" placeholder="全部状态" clearable><el-option v-for="(label, value) in orderStatusLabel" :key="value" :label="label" :value="value" /></el-select><el-button @click="load(1)">查询</el-button></div>
    <div :class="$style.table"><el-table v-loading="loading" :data="items"><el-table-column label="订单信息" min-width="205"><template #default="{ row }"><div :class="$style.order"><b>{{ row.orderNo }}</b><span>{{ formatDateTime(row.createdAt) }}</span></div></template></el-table-column><el-table-column label="用户" min-width="180"><template #default="{ row }"><div :class="$style.order"><b>{{ row.user.nickname || '未设置昵称' }}</b><span>{{ row.user.email }}</span></div></template></el-table-column><el-table-column label="收件人" width="110"><template #default="{ row }">{{ row.receiver }}</template></el-table-column><el-table-column label="商品" width="80"><template #default="{ row }">{{ row.items.reduce((n: number, line: any) => n + line.quantity, 0) }} 件</template></el-table-column><el-table-column label="实付" width="115"><template #default="{ row }"><b>¥{{ row.payableAmount.toFixed(2) }}</b></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="orderStatusType[row.status as OrderStatus]">{{ orderStatusLabel[row.status as OrderStatus] }}</el-tag></template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="{ row }"><el-button link @click="detail(row)">查看</el-button><el-button v-if="row.status === 'PENDING_SHIPMENT'" link type="primary" @click="change(row, 'SHIPPED', '发货')">确认发货</el-button><el-button v-if="row.status === 'SHIPPED'" link type="success" @click="change(row, 'COMPLETED', '完成')">完成订单</el-button><el-button v-if="row.status === 'PENDING_PAYMENT'" link type="danger" @click="change(row, 'CANCELLED', '取消')">取消</el-button></template></el-table-column></el-table></div>
    <el-pagination v-if="pagination.totalPages > 1" background layout="prev, pager, next" :current-page="pagination.page" :page-size="pagination.pageSize" :total="pagination.total" @current-change="load" />
    <el-drawer v-model="detailVisible" title="订单详情" size="min(520px, 92vw)"><template v-if="current"><div :class="$style.detailTop"><span>订单号 {{ current.orderNo }}</span><el-tag :type="orderStatusType[current.status]">{{ orderStatusLabel[current.status] }}</el-tag><strong>¥{{ current.payableAmount.toFixed(2) }}</strong></div><h3>商品明细</h3><div :class="$style.lines"><div v-for="line in current.items" :key="line.id"><img :src="line.image" :alt="line.productName" /><div><b>{{ line.productName }}</b><span>{{ line.skuName }} × {{ line.quantity }}</span></div><strong>¥{{ line.subtotal.toFixed(2) }}</strong></div></div><h3>收货信息</h3><div :class="$style.address"><b>{{ current.receiver }} · {{ current.phone }}</b><span>{{ current.province }} {{ current.city }} {{ current.district }} {{ current.addressDetail }}</span></div><div :class="$style.drawerActions"><el-button v-if="current.status === 'PENDING_SHIPMENT'" type="primary" @click="change(current, 'SHIPPED', '发货')">确认发货</el-button><el-button v-if="current.status === 'SHIPPED'" type="success" @click="change(current, 'COMPLETED', '完成')">完成订单</el-button></div></template></el-drawer>
  </section>
</template>

<style module lang="scss">
.heading{margin-bottom:24px;span{color:#5f7d6c;font-size:11px;letter-spacing:.2em;font-weight:800}h1{margin:8px 0 5px;font-size:30px;letter-spacing:-.04em}p{margin:0;color:#7d8881;font-size:13px}}.toolbar{margin-bottom:14px;padding:14px;display:flex;gap:10px;background:#fff;border:1px solid #e0e6e0;border-radius:13px;:global(.el-input){width:310px}:global(.el-select){width:160px}}.table{overflow:hidden;background:#fff;border:1px solid #e0e6e0;border-radius:14px}.order{display:grid;gap:5px;b{font-size:12px}span{color:#8c9690;font-size:10px}}section>:global(.el-pagination){justify-content:center;margin-top:24px}.detailTop{padding:18px;display:grid;grid-template-columns:1fr auto;gap:8px;border-radius:13px;background:#f3f6f2;span{color:#6c7871;font-size:12px}strong{grid-column:1/-1;font-size:28px;color:#94432d}}h3{margin:28px 0 12px;font-size:14px}.lines{display:grid;gap:11px}.lines>div{display:grid;grid-template-columns:52px 1fr auto;gap:11px;align-items:center;padding-bottom:11px;border-bottom:1px solid #edf0ed;img{width:52px;height:52px;object-fit:cover;border-radius:8px}div{display:grid;gap:5px}b{font-size:12px}span{color:#8c9690;font-size:10px}strong{font-size:12px}}.address{padding:15px;display:grid;gap:7px;border:1px solid #e1e7e1;border-radius:10px;b{font-size:12px}span{color:#6f7b74;font-size:12px;line-height:1.6}}.drawerActions{margin-top:24px;display:flex;justify-content:flex-end}@media(max-width:600px){.toolbar{flex-wrap:wrap}.toolbar :global(.el-input){width:100%}.heading p{display:none}}
</style>
