<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { Plus, Search } from '@element-plus/icons-vue'
import { adminApi, type ProductPayload } from '@/api/admin'
import { productApi } from '@/api/product'
import type { AdminProduct, Category, Pagination, ProductStatus } from '@/types'

const loading = ref(true), saving = ref(false), visible = ref(false)
const items = ref<AdminProduct[]>([]), categories = ref<Category[]>([])
const pagination = ref<Pagination>({ page: 1, pageSize: 10, total: 0, totalPages: 0 })
const filters = reactive({ keyword: '', status: '' as '' | ProductStatus })
const formRef = ref<FormInstance>(), editingId = ref<number | null>(null)
const blank = (): ProductPayload => ({ categoryId: 0, name: '', subtitle: '', description: '', cover: '', price: 0, originalPrice: null, status: 'DRAFT', skus: [{ skuCode: '', name: '默认规格', specs: {}, price: 0, stock: 0 }] })
const form = reactive<ProductPayload>(blank())
const rules: FormRules = { categoryId: [{ required: true, message: '请选择分类', trigger: 'change' }], name: [{ required: true, message: '请输入商品名称', trigger: 'blur' }], description: [{ required: true, message: '请输入商品描述', trigger: 'blur' }], cover: [{ required: true, message: '请输入封面地址', trigger: 'blur' }] }
const statusLabel: Record<ProductStatus, string> = { DRAFT: '草稿', ACTIVE: '在售', INACTIVE: '已下架' }
const statusType: Record<ProductStatus, '' | 'success' | 'info'> = { DRAFT: '', ACTIVE: 'success', INACTIVE: 'info' }

async function load(page = 1) { loading.value = true; try { const result = await adminApi.products({ page, pageSize: 10, keyword: filters.keyword || undefined, status: filters.status || undefined }); items.value = result.data.items; pagination.value = result.data.pagination } finally { loading.value = false } }
function resetForm() { Object.assign(form, blank()); editingId.value = null; formRef.value?.clearValidate() }
function create() { resetForm(); visible.value = true }
function edit(item: AdminProduct) { editingId.value = item.id; Object.assign(form, { categoryId: item.categoryId, name: item.name, subtitle: item.subtitle || '', description: item.description, cover: item.cover, price: item.price, originalPrice: item.originalPrice, status: item.status, skus: item.skus.map((sku) => ({ id: sku.id, skuCode: sku.skuCode, name: sku.name, specs: sku.specs || {}, price: sku.price, stock: sku.stock })) }); visible.value = true }
function addSku() { form.skus.push({ skuCode: '', name: '', specs: {}, price: form.price, stock: 0 }) }
function removeSku(index: number) { if (form.skus.length > 1) form.skus.splice(index, 1) }
async function save() { if (!await formRef.value?.validate()) return; if (form.skus.some((sku) => !sku.skuCode || !sku.name)) return ElMessage.warning('请完善 SKU 编码和名称'); saving.value = true; try { if (editingId.value) await adminApi.updateProduct(editingId.value, form); else await adminApi.createProduct(form); ElMessage.success(editingId.value ? '商品保存成功' : '商品创建成功'); visible.value = false; await load(editingId.value ? pagination.value.page : 1) } finally { saving.value = false } }
async function toggle(item: AdminProduct) { const next: ProductStatus = item.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'; await ElMessageBox.confirm(`确定将“${item.name}”${next === 'ACTIVE' ? '上架' : '下架'}吗？`, '更新商品状态', { type: 'warning' }); await adminApi.setProductStatus(item.id, next); ElMessage.success('商品状态已更新'); await load(pagination.value.page) }
onMounted(async () => { const result = await productApi.categories(); categories.value = result.data; await load() })
</script>

<template>
  <section><div :class="$style.heading"><div><span>PRODUCTS</span><h1>商品管理</h1><p>维护商品资料、规格库存与销售状态。</p></div><el-button type="primary" :icon="Plus" @click="create">新增商品</el-button></div>
    <div :class="$style.toolbar"><el-input v-model="filters.keyword" placeholder="搜索商品名称" clearable :prefix-icon="Search" @keyup.enter="load(1)" /><el-select v-model="filters.status" placeholder="全部状态" clearable><el-option label="草稿" value="DRAFT" /><el-option label="在售" value="ACTIVE" /><el-option label="已下架" value="INACTIVE" /></el-select><el-button @click="load(1)">查询</el-button></div>
    <div :class="$style.table"><el-table v-loading="loading" :data="items"><el-table-column label="商品" min-width="260"><template #default="{ row }"><div :class="$style.product"><img :src="row.cover" :alt="row.name" /><div><b>{{ row.name }}</b><span>{{ row.subtitle || '暂无副标题' }}</span></div></div></template></el-table-column><el-table-column prop="category.name" label="分类" width="120" /><el-table-column label="价格" width="110"><template #default="{ row }"><b>¥{{ row.price.toFixed(2) }}</b></template></el-table-column><el-table-column prop="stock" label="库存" width="80" /><el-table-column prop="salesCount" label="销量" width="80" /><el-table-column label="状态" width="90"><template #default="{ row }"><el-tag :type="statusType[row.status as ProductStatus]">{{ statusLabel[row.status as ProductStatus] }}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link :type="row.status === 'ACTIVE' ? 'danger' : 'success'" @click="toggle(row)">{{ row.status === 'ACTIVE' ? '下架' : '上架' }}</el-button></template></el-table-column></el-table></div>
    <el-pagination v-if="pagination.totalPages > 1" background layout="prev, pager, next" :current-page="pagination.page" :page-size="pagination.pageSize" :total="pagination.total" @current-change="load" />
    <el-dialog v-model="visible" :title="editingId ? '编辑商品' : '新增商品'" width="min(760px, calc(100vw - 28px))" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div :class="$style.formGrid"><el-form-item label="商品名称" prop="name"><el-input v-model="form.name" /></el-form-item><el-form-item label="商品分类" prop="categoryId"><el-select v-model="form.categoryId" style="width:100%"><el-option-group v-for="group in categories" :key="group.id" :label="group.name"><el-option v-for="child in group.children" :key="child.id" :label="child.name" :value="child.id" /></el-option-group></el-select></el-form-item><el-form-item label="商品副标题"><el-input v-model="form.subtitle" /></el-form-item><el-form-item label="销售状态"><el-select v-model="form.status" style="width:100%"><el-option label="草稿" value="DRAFT" /><el-option label="在售" value="ACTIVE" /><el-option label="已下架" value="INACTIVE" /></el-select></el-form-item><el-form-item label="封面图片地址" prop="cover" :class="$style.full"><el-input v-model="form.cover" placeholder="/images/products/example.jpg" /></el-form-item><el-form-item label="商品描述" prop="description" :class="$style.full"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item><el-form-item label="展示价"><el-input-number v-model="form.price" :min="0" :precision="2" controls-position="right" /></el-form-item><el-form-item label="划线价"><el-input-number v-model="form.originalPrice" :min="0" :precision="2" controls-position="right" /></el-form-item></div><div :class="$style.skuHead"><div><b>SKU 规格</b><span>商品总库存将按各规格相加</span></div><el-button size="small" @click="addSku">添加规格</el-button></div><div v-for="(sku, index) in form.skus" :key="sku.id || index" :class="$style.sku"><el-input v-model="sku.name" placeholder="规格名称" /><el-input v-model="sku.skuCode" placeholder="SKU 编码" /><el-input-number v-model="sku.price" :min="0" :precision="2" placeholder="售价" /><el-input-number v-model="sku.stock" :min="0" :precision="0" placeholder="库存" /><el-button link type="danger" :disabled="form.skus.length === 1" @click="removeSku(index)">移除</el-button></div></el-form><template #footer><el-button @click="visible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存商品</el-button></template></el-dialog>
  </section>
</template>

<style module lang="scss">
.heading { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 24px; span { color:#5f7d6c;font-size:11px;letter-spacing:.2em;font-weight:800 } h1{margin:8px 0 5px;font-size:30px;letter-spacing:-.04em} p{margin:0;color:#7d8881;font-size:13px} }.toolbar { margin-bottom: 14px; padding: 14px; display:flex;gap:10px;background:#fff;border:1px solid #e0e6e0;border-radius:13px; :global(.el-input){width:260px} :global(.el-select){width:150px} }.table { overflow:hidden;background:#fff;border:1px solid #e0e6e0;border-radius:14px; }.product{display:flex;align-items:center;gap:11px;img{width:50px;height:50px;object-fit:cover;border-radius:8px}div{min-width:0;display:grid;gap:5px}b,span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}span{color:#8b958f;font-size:11px}} section > :global(.el-pagination){justify-content:center;margin-top:24px}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.full{grid-column:1/-1}.skuHead{margin:5px 0 10px;display:flex;justify-content:space-between;align-items:center;div{display:grid;gap:3px}span{color:#929c96;font-size:11px}}.sku{display:grid;grid-template-columns:1fr 1.2fr 130px 120px 50px;gap:8px;margin-bottom:9px;align-items:center}
@media(max-width:700px){.heading p{display:none}.toolbar{flex-wrap:wrap}.toolbar :global(.el-input){width:100%}.formGrid{grid-template-columns:1fr}.full{grid-column:auto}.sku{grid-template-columns:1fr 1fr}.sku :global(.el-button){justify-self:start}}
</style>
